# Generated by Django 5.2.16 on 2026-07-21 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_off_duty', models.FloatField()),
                ('total_sleeper', models.FloatField()),
                ('total_driving', models.FloatField()),
                ('total_on_duty', models.FloatField()),
                ('total_miles', models.FloatField()),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(max_length=255)),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('current_cycle_used', models.FloatField(help_text='Hours already used in the 70/8 cycle')),
                ('total_distance_miles', models.FloatField()),
                ('total_drive_hours', models.FloatField(help_text='HOS basis: distance / 55 mph')),
                ('total_days', models.IntegerField()),
                ('cycle_hours_remaining', models.FloatField()),
                ('provider_eta_hours', models.FloatField(blank=True, help_text="Routing provider's own estimate. Display only -- never used for HOS.", null=True)),
                ('geometry', models.JSONField(default=list, help_text='[[lat, lng], ...] polyline')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DutySegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('off_duty', 'Off duty'), ('sleeper', 'Sleeper berth'), ('driving', 'Driving'), ('on_duty', 'On duty (not driving)')], max_length=20)),
                ('start_minute', models.IntegerField(help_text='Minutes from midnight, 0-1440')),
                ('end_minute', models.IntegerField(help_text='Minutes from midnight, 0-1440')),
                ('remark', models.CharField(blank=True, max_length=255)),
                ('log_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='api.logday')),
            ],
            options={
                'ordering': ['start_minute'],
            },
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('start', 'Start'), ('pickup', 'Pickup'), ('dropoff', 'Dropoff'), ('fuel', 'Fuel'), ('break_30', '30-minute break'), ('rest_10', '10-hour rest'), ('restart_34', '34-hour restart')], max_length=20)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('arrive_at', models.DateTimeField()),
                ('depart_at', models.DateTimeField()),
                ('sequence', models.IntegerField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='api.trip')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.AddField(
            model_name='logday',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='api.trip'),
        ),
    ]
