# Generated by Django 5.2.16 on 2026-07-22 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='provider_eta_source',
            field=models.CharField(blank=True, help_text="Which provider and profile produced the route, e.g. 'Geoapify truck'. Stored rather than derived so an old trip keeps reporting the provider that actually served it.", max_length=64),
        ),
    ]
