# Generated by Django 5.2.16 on 2026-07-23 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_trip_provider_eta_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='resolved_locations',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
